name: pancancer-genomics

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - xgboost
  - pip
  - pip:
      - ucimlrepo
